### PR TITLE
Add new Elastix/ElasticSearch store.

### PR DESCRIPTION
**Pull request by BDQ**
This adds a new store using Elastix / ElasticSearch, it's working but there's a couple of places I'm not wild about:

1) in the `setup` function - I couldn't figure out if there's someway to set default opts - any suggestions?

2) A had to add timer.sleep to ensure the doctests pass consistently, as ES can take a few 100 ms to index new values.

### CODE REVIEW

**Comment by christhekeele** [comment]
Hey, sorry I only just noticed this! I've been swamped.

I'll look over it this weekend and think through those pain points you mention.

Many thanks! 💟 💟 💟

**Comment by christhekeele** [comment]
Hi @BDQ! Just looked over this.

1. The main purpose of the (poorly documented) `setup` function is to take the initial `options` provided by the user, and [convert them](https://github.com/christhekeele/mnemonix/blob/master/lib/mnemonix/store/server.ex#L44) to some `state` to store in the `Mnemonix.Store` struct for reference later. (The initial options provided by the user, pre-modification, are available under the `options` property.)

    Most of the other stores use this function to massage configuration specific to that store, set defaults values if not provided essential to that store, pass in extras to that store's configuration, and return the result of some `new` (if in-memory) or `start_link` (if out-of-memory) invocation.

    It doesn't look like `Elastix` really has any such API, though––every interaction must provide all details needed to connect. This is pretty different from, say, the ETS store that massages a *bunch* of variables and then tries to create the store, or the Redix store that passes all but the most important url option straight into the library for processing.

    What I'd do in your case is to create an internal `Mnemonix.Stores.Elastix.Conn` struct with the defaults you provide in your private `config` function, create a new instance of it in the `setup`, function, apply any overrides present in the keyword `options` provided to the function, and return that as the store's state.

    Then in your implementation of delete/fetch/put you can pattern match the values of that struct back out to invoke the `Elastix` API.

2. That's an interesting dilemma, caused entirely by my laziness. In the future I want to have every function of every store unit tested, not just the core delete/fetch/put ones. In my laziness, though, `use Mnemonix.Store.Behaviour` just implements all the derived functions, and the specs just use those doctests to make sure everything's working.

    This pattern has worked well to date, but it [does fall apart](https://github.com/christhekeele/mnemonix/blob/master/README.md#doctests) in complicated setup testing scenarios. Your store is the first example where it can't be [hacked around](https://github.com/christhekeele/mnemonix/blob/master/test/mnemonix/stores/dets_test.exs#L4-L10), I suspect.

    However, it doesn't feel right to enforce the `:timer.sleep(2000)` wait at the Mnemonix level to me.  I feel as if that is more of an ElasticSearch caveat, that we should document in the `Mnemonix.Stores.Elastix` level, but not enforce ourselves.

    What I would recommend is documenting the need for the wait, but removing the wait from the store implementation, commenting out the doctests, and writing some simple delete/fetch/put tests in their place inside `Mnemonix.Stores.Elastix.Test`, where you wait there before each test assertion.

    If you put those three core functions in, I'll beef those tests up when I get around to better testing the rest of the generated functions for all stores.

My final note––it looks like you're [using the `Raw`](https://github.com/BDQ/mnemonix/blob/elastix/lib/mnemonix/stores/elastix.ex#L25) translator for `Elastix`.  This is a [no-op](https://github.com/christhekeele/mnemonix/blob/master/lib/mnemonix/store/translators/raw.ex#L3) (de)serializer for in-memory stores that can handle any erlang or Elixir term thrown at them. Is this supported by `Elastix`, or does it require that you (de)serialize terms into some specific format first?

If not, that's really cool, it'd be the first out-of-memory store to support that. Otherwise, there's a naïve translator you can use instead that just [uses the external term format](https://github.com/christhekeele/mnemonix/blob/master/lib/mnemonix/store/translators/term.ex).

Thanks again for contributing, I'm excited to add support for ElasticSearch!

**Comment by BDQ** [comment]
Hey @christhekeele - thanks for the detailed feedback.

I think I've covered everything you've suggested, take a look and let me know. I much happier with the testing setup now that I was able to drop the doctests. Everything is green for me locally, including the unrelated stuff thats failing on Travis - not sure what's going on there.

Regarding the translator and using `Raw` - Raw is enough, as I do have a VERY naïve check within the [put function] (https://github.com/BDQ/mnemonix/blob/elastix/lib/mnemonix/stores/elastix.ex#L94) that wraps anything that isn't a Map into one. Elastix is encoding that as json/string later away, so it works fine.

**Comment by christhekeele** [comment]
Aside from some stylistic stuff I'll tweak in post, this looks good. My only remaining concern is about the translator––maybe you'd know more about this?

You're [wrapping arbitrary non-map values](https://github.com/christhekeele/mnemonix/pull/36/files#diff-6e072b0b021a39ce4e8f8d512f278b18R94) in maps and relying on Elastix's [default serialization strategy](https://github.com/werbitzky/elastix/blob/master/lib/elastix/document.ex#L14) which just delegates the work to the Poison Encoder [protocol](https://github.com/devinus/poison/blob/master/lib/poison/encoder.ex#L78).

I see a [fallback](https://github.com/devinus/poison/blob/master/lib/poison/encoder.ex#L79) to [Any](https://github.com/devinus/poison/blob/master/lib/poison/encoder.ex#L341) implementation but I'm not sure how that handles elixir primitives not already implemented in that file (like Pid) and user-land structs. Do you know?

**Comment by christhekeele** [comment]
Hey @BDQ!

Boy it's been a while. Picking this up again:

```elixir
pid = self
Poison.encode!(%{"_value" => pid})
```

This does raise, so I'm switching out the translator for the term one.

After researching how other libraries test elastic search integration, I'm going to add an option when starting up the store to force it to auto-refresh after every request, by appending `?refresh` to the urls, and turn that on in the tests. I took this strategy from their issues, discussed [here](https://github.com/elastic/elasticsearch/issues/1063#issuecomment-218185247).

I'm thinking about having this auto-refresh mode be the default for Mnemonix, to make the store behave more like the Map analog, but I don't have use-cases to inform this decision––do you have any opinions?

I'm going to implement these changes on top of your efforts and merge soon, and release them after giving you some time to give me feedback on the question above. Thanks again for the PR!

**Comment by christhekeele** [comment]
Regarding the translator's serialization:

The purpose of Mnemonix is more to allow a variety of systems act like key-value stores, but a secondary goal is to allow pushing and pulling data from external systems that they may serve as a bridge to others.

With that in mind, it does seem a lot less useful to have a term-serialized binary blob in elasticsearch instead of a structured document. I will do more work to ensure that is the case, and revise other stores (specifically redis) to try to use smarter serializers.

**Comment by christhekeele** [comment]
Well crap, I explicitly pulled your commits into the now-default `development` branch (since I always intended PRs to be made against it, and this was made against master) in such a way that even as I added some things to it to prepare for release, the PR would be counted as merged. Unfortunately I forgot about that and rebased at some point, shifting the shas.

So you're [in the history](https://github.com/christhekeele/mnemonix/compare/bf0ea3c7a78227881b459edc3ab3a2fb566fe7e4...f47ce1da484050bff415bbc96fa803bec77d2809) but this PR has to be marked as `Closed` rather than `Merged` to be resolved, mea culpa.

**Pull request closed without merging**
