### PR TITLE
Implement a null store

### PR DESCRIPTION
**Pull request by rzane**
@coderrick and I implemented a null store.

The doctest seems to be acting a bit crazy though... not sure why it seems to fail. The actual test passes with flying colors though. The doctest error is cryptic, so I'm not sure why it seems to be failing.

### CODE REVIEW

**Comment by rzane** [comment]
The doctest wackiness seems to be related to the behaviour. Also, I'm considering pulling the serialization/deserialization functions into a module. Thoughts?

**Comment by christhekeele** [comment]
@rzane I was considering making a behaviour for them, and packaging up the two existing ones. Something like a `Mnemonix.Store.Translator` namespace with the in-memory and term behaviours. I'm not sure if that'd prove a useful level of abstraction, though. Pulling them out into a module seems like a good way to start.

**Comment by christhekeele** [comment]
You're right, the test failures are because the behaviour introduces its [own doctests](https://github.com/christhekeele/mnemonix/blob/master/lib/mnemonix/store/behaviour.ex#L35-L43). This was useful back when I was fussing around with the interfaces of the library a lot, because

- it required me to keep my docs up to date
- it ensured I changed the code for all stores when I changed a behaviour
- it allowed me to spot stores that weren't behaving identically easily

The problem is, of course, that the null store doesn't behave identically. I believe you can fix this by adding your own `@docs` to the null store's functions where the behaviour diverges.

**Comment by rzane** [comment]
Okay, I implemented `Mnemonix.Store.Translator.Raw` as a macro. And I'll address the doctests.

**Comment by christhekeele** [comment]
@rzane Don't worry too much about travis–seems I've hit a github API limit, so the builds fail. As long as the tests pass, we're golden.

**Comment by christhekeele** [comment]
Thanks! :heart_decoration::heart_decoration::heart_decoration::heart_decoration::heart_decoration:

**Pull request merged**
